// engine/src/report/templates.ts
import type { ChartConfig } from './charts';

interface ReportSection {
  title: string;
  content: string;        // raw HTML
  chart?: ChartConfig;    // optional chart
  chartId?: string;       // canvas element id
}

export function renderReport(opts: {
  title: string;
  subtitle?: string;
  date: string;
  sections: ReportSection[];
}): string {
  const chartScripts = opts.sections
    .filter(s => s.chart && s.chartId)
    .map(s => `new Chart(document.getElementById('${s.chartId}'), ${JSON.stringify(s.chart)});`)
    .join('\n    ');

  const sectionsHtml = opts.sections.map(s => `
  <section class="mb-8">
    <h2 class="text-xl font-semibold text-gray-200 mb-4">${s.title}</h2>
    ${s.chart && s.chartId ? `<div class="bg-gray-900 rounded-lg p-4 mb-4"><canvas id="${s.chartId}"></canvas></div>` : ''}
    <div class="text-gray-300">${s.content}</div>
  </section>`).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>finstack — ${opts.title}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <style>
    body { font-family: 'SF Mono', 'Monaco', 'Inconsolata', 'Fira Mono', monospace; }
  </style>
</head>
<body class="bg-gray-950 text-gray-100 min-h-screen">
  <div class="max-w-4xl mx-auto px-6 py-8">
    <header class="mb-8 border-b border-gray-800 pb-4">
      <h1 class="text-2xl font-bold text-white">${opts.title}</h1>
      ${opts.subtitle ? `<p class="text-gray-400 mt-1">${opts.subtitle}</p>` : ''}
      <p class="text-gray-500 text-sm mt-2">${opts.date} · Generated by finstack</p>
    </header>

    ${sectionsHtml}

    <footer class="mt-12 pt-4 border-t border-gray-800 text-gray-600 text-xs">
      Generated by finstack v0.5.0 · ${opts.date}
    </footer>
  </div>

  <script>
    Chart.defaults.color = '#9ca3af';
    Chart.defaults.borderColor = '#374151';
    ${chartScripts}
  </script>
</body>
</html>`;
}
